sudo: required

language: python
python: 2.7

services:
  - docker

before_install:
  - docker build --build-arg REPO_DIR=. -t complynx/pilot-test -f tools/docker/Dockerfile .
  - docker run complynx/pilot-test bash -c "cd /repo; pip install tox; tools/install_venv.sh; tools/with_venv.sh pip install tox; tools/with_venv.sh tox"

script:
  - tools/with_venv.sh tox

after_success:
  - pip install coveralls
- coveralls